### ISSUE TITLE
Your project is great, but I get an error when I run the demo. What is the reason? Thanks a lot.

### ISSUE THREAD

**Issue by wby920920** [jiupinjia/stylized-neural-painting#6]
![image](https://user-images.githubusercontent.com/32837843/99910230-ceb6e800-2d27-11eb-9d8f-462d0d897a28.png)
Your project is great, but I get an error when I run the demo. What is the reason? Thanks a lot.

**Comment by jiupinjia** [comment]
Hi, thanks for your feedback. It seems you are running in a CPU mode. Do you have a cuda device available?

**Comment by wby920920** [comment]
Yes, I found the same error when I started using gpu. Then I changed the device in the demo to cpu and the same error occurred.

**Comment by wby920920** [comment]
> 嗨，谢谢您的反馈。看来您正在CPU模式下运行。您有可用的cuda设备吗？

![image](https://user-images.githubusercontent.com/32837843/99914960-bcdf4000-2d3b-11eb-94d5-2d8ea6186351.png)

**Comment by wby920920** [comment]
![image](https://user-images.githubusercontent.com/32837843/99914969-ce284c80-2d3b-11eb-8321-183688cc4ef7.png)

**Comment by jiupinjia** [comment]
It seems you are using a pretty old version of PyTorch. I just tried to downgrade my PyTorch and saw the same error as you did. I finally found that the problem lies in the inconsistency of the data type (cuda float32 vs cuda float 64) between the two variables (img_batch and G_final_pred_canvas). I have made a minor update on the initializing of the img_batch, and this time I believe the problem has been fixed. You git-clone to your local machine and try it again. Please tell me whether it works fine this time. Thanks!

**Comment by wby920920** [comment]
> It seems you are using a pretty old version of PyTorch. I just tried to downgrade my PyTorch and saw the same error as you did. I finally found that the problem lies in the inconsistency of the data type (cuda float32 vs cuda float 64) between the two variables (img_batch and G_final_pred_canvas). I have made a minor update on the initializing of the img_batch, and this time I believe the problem has been fixed. You git-clone to your local machine and try it again. Please tell me whether it works fine this time. Thanks!

Thank you very much for your reply. But it is a pity that I cloned your project again, and the same error still appears. I am trying to update the pytorch installation package to the latest version.

**Comment by jiupinjia** [comment]
Can you please show me your error report this time?

**Comment by wby920920** [comment]
> Can you please show me your error report this time?

Hello, first of all thank you for paying attention to my question. When I use the old version (pytorch1.2), an error occurs as shown in the figure. When I use the latest version of pytorch (1.7), the code can run smoothly.
![image](https://user-images.githubusercontent.com/32837843/99974852-7261d000-2ddc-11eb-893e-b02beff3167d.png)

**Comment by jiupinjia** [comment]
It is weird that an older version of PyTorch still has such an error since I have made updates accordingly.
Can you show me what your line 241 of utils.py looks like? Thanks.

**Comment by wby920920** [comment]
> It is weird that an older version of PyTorch still has such an error since I have made updates accordingly.
> Can you show me what your line 241 of utils.py looks like? Thanks.

I found that the project I downloaded is different from the 241 line on github. After I modified it, it can run with the old version of Pytorch. I am very sorry for the inconvenience caused by my negligence.

**Comment by jiupinjia** [comment]
That's fine! Pls feel free to reach out to me if you have any further questions. Cheers!

**Comment by JohnHack8** [comment]
Good afternoon, your project is very interesting. I am new to computer vision, so there are a few questions. 
1. The project will not work without CUDA, using CPU only? 
2. What is an 'painter' in this line: from painter import *? Some kind of library?
Thanks.

**Comment by jiupinjia** [comment]
Hi @JohnHack8, Thanks for your question. I strongly recommend using a GPU since the computation would be heavy for a CPU. The painter module imported here is exactly from the file painter.py. We need some prefined classes and functions to help with such a task. Thanks!

**Comment by jiupinjia** [comment]
Hi @JohnHack8, PyTorch-CPU mode is now supported! You can try out on your local machine without any GPU cards. But please note that you still need PyTorch installed if you run on CPU mode. You can simply follow the instructions in the README file and the code will automatically detect whether there will be any GPU cards available. If there is no GPU, the code will run on the CPU automatically. Please let me know if there is any problem. Thanks!

**Comment by JohnHack8** [comment]
Hi jiupinjia. It's great news. Thanks!
